import type {Metadata} from 'next';
import {Geist} from 'next/font/google';
import type {ReactNode} from 'react';
import '@/styles/general.scss';

const geistSans = Geist({
    variable: '--f-geist-sans',
    subsets: ['latin']
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

export default function RootLayout({
    children
}: Readonly<{
    children: ReactNode;
}>) {
    return (
        <html lang={'en'} className={geistSans.variable}>
            <body>{children}</body>
        </html>
    );
}
